<?php
/**
 * Created by PhpStorm.
 * User: m.borodulin
 * Date: 17.08.2018
 * Time: 12:55
 */

namespace pradex;


class ApplicationRegistryTest extends ApplicationRegistry
{
    public function getPDO()
    {
       echo "ok!";
        if (!isset($this->pdo)){
            $this->pdo = new \PDO(
                'mysql:dbname=pooboxinbo_avt',
                'pooboxinbo_avt',
                'interrUpt-9',
                array(
                    \PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8',
                )
            );
        }
        \ReflectionObject::export($this->pdo);
        return $this->pdo;
        //return parent::getPDO(); // TODO: Change the autogenerated stub
    }
}